networks:
  api-network:
    driver: bridge

services:
  boheme:
    env_file: .env
    container_name: boheme
    restart: always
    build: ./apps/boheme
    environment:
      PORT: 3017
    ports:
      - "3017:3017"
    networks:
      - api-network
    depends_on:
      - mongo

  canto:
    env_file: .env
    container_name: canto
    restart: always
    build: ./apps/canto
    environment:
      PORT: 3045
    ports:
      - "3045:3045"
    networks:
      - api-network
    depends_on:
      - mongo

  jazzola:
    env_file: .env
    container_name: jazzola
    restart: always
    build: ./apps/jazzola
    environment:
      PORT: 3342
    ports:
      - "3342:3342"
    networks:
      - api-network
    depends_on:
      - mongo

  swing-family:
    env_file: .env
    container_name: swing-family
    restart: always
    build: ./apps/swing-family
    environment:
      PORT: 3047
    ports:
      - "3047:3047"
    networks:
      - api-network
    depends_on:
      - mongo

  trio-rsh:
    env_file: .env
    container_name: trio-rsh
    restart: always
    build: ./apps/trio-rsh
    environment:
      PORT: 3027
    ports:
      - "3027:3027"
    networks:
      - api-network
    depends_on:
      - mongo

  west-side-trio:
    env_file: .env
    container_name: west-side-trio
    restart: always
    build: ./apps/west-side-trio
    environment:
      PORT: 7027
    ports:
      - "7027:7027"
    networks:
      - api-network
    depends_on:
      - mongo

  managr:
    env_file: .env
    container_name: managr
    restart: always
    build: ./apps/managr
    environment:
      PORT: 3091
      API_URL: $MANAGR_API_URL
    ports:
      - "3091:3091"
    networks:
      - api-network
    depends_on:
      - mongo

  managr-api:
    env_file: .env
    container_name: managr-api
    restart: always
    build: ./apps/managr-api
    environment:
      PORT: 3092
    ports:
      - "3092:3092"
    networks:
      - api-network
    depends_on:
      - mongo
      - redis

  mongo:
    image: 'mongo:4.4.18'
    container_name: mongo
    restart: always
    platform: linux/arm64
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
    ports:
      - 27029:27017
    volumes:
      - ./data/mongo:/bitnami/mongodb
    networks:
      - api-network

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    restart: always
    user: "1001"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - api-network
    command: /opt/bitnami/scripts/redis/run.sh --appendonly no
    volumes:
      - ./data/redis:/bitnami/redis/data

