networks:
  api-network:
    driver: bridge

services:
  boheme:
    env_file: .env
    restart: always
    build: ./apps/boheme
    environment:
      PORT: 3017
    ports:
      - "3017:3017"
    networks:
      - api-network
    depends_on:
      - mongo

  jazzola:
    env_file: .env
    restart: always
    build: ./apps/jazzola
    environment:
      PORT: 3342
    ports:
      - "3342:3342"
    networks:
      - api-network
    depends_on:
      - mongo

  canto:
    env_file: .env
    restart: always
    build: ./apps/canto
    environment:
      PORT: 3045
    ports:
      - "3045:3045"
    networks:
      - api-network
    depends_on:
      - mongo

  swing-family:
    env_file: .env
    restart: always
    build: ./apps/swing-family
    environment:
      PORT: 3047
    ports:
      - "3047:3047"
    networks:
      - api-network
    depends_on:
      - mongo

  west-side-trio:
    env_file: .env
    restart: always
    build: ./apps/west-side-trio
    environment:
      PORT: 7027
    ports:
      - "7027:7027"
    networks:
      - api-network
    depends_on:
      - mongo

  mongo:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
      - MONGODB_EXTRA_USERNAMES=boheme,mpquartet,jazzola,swing-family,trio-rsh,west-side-trio
      - MONGODB_EXTRA_PASSWORDS=${MONGODB_BOHEME_PASSWORD};${MONGODB_MPQUARTET_PASSWORD};${MONGODB_JAZZOLA_PASSWORD};${MONGODB_SWINGFAMILY_PASSWORD};${MONGODB_TRIORSH_PASSWORD};${MONGODB_WESTSIDETRIO_PASSWORD}
      - MONGODB_EXTRA_DATABASES=boheme,mpquartet,jazzola,swing-family,trio-rsh,west-side-trio
    ports:
      - 27029:27017
    # volumes:
    #   - ./data/mongo:/bitnami/mongodb
    networks:
      - api-network

  webserver:
    depends_on:
      - canto
      - boheme
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d:ro
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/certbot:/var/www/certbot
    networks:
      - api-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/certbot:/var/www/certbot

  # redis:
  #   image: 'bitnami/redis:latest'
  #   env_file: .env.docker
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - 6369:6379
  #   networks:
  #     - api-network
  #   volumes:
  #     - ./data/redis:/bitnami/redis


volumes:
  certbot_etc:
  redis_data:
  certbot_certs:
