networks:
  api-network:
    driver: bridge

services:
  boheme:
    env_file: .env
    restart: always
    build: ./apps/boheme
    environment:
      PORT: 3017
    ports:
      - "3017:3017"
    networks:
      - api-network
    depends_on:
      - mongo

  canto:
    env_file: .env
    restart: always
    build: ./apps/canto
    environment:
      PORT: 3045
    ports:
      - "3045:3045"
    networks:
      - api-network
    depends_on:
      - mongo

  jazzola:
    env_file: .env
    restart: always
    build: ./apps/jazzola
    environment:
      PORT: 3342
    ports:
      - "3342:3342"
    networks:
      - api-network
    depends_on:
      - mongo

  swing-family:
    env_file: .env
    restart: always
    build: ./apps/swing-family
    environment:
      PORT: 3047
    ports:
      - "3047:3047"
    networks:
      - api-network
    depends_on:
      - mongo

  trio-rsh:
    env_file: .env
    restart: always
    build: ./apps/trio-rsh
    environment:
      PORT: 3027
    ports:
      - "3027:3027"
    networks:
      - api-network
    depends_on:
      - mongo

  west-side-trio:
    env_file: .env
    restart: always
    build: ./apps/west-side-trio
    environment:
      PORT: 7027
    ports:
      - "7027:7027"
    networks:
      - api-network
    depends_on:
      - mongo

  managr:
    env_file: .env
    restart: always
    build: ./apps/managr
    environment:
      PORT: 3091
      API_URL: $MANAGR_API_URL
    ports:
      - "3091:3091"
    networks:
      - api-network
    depends_on:
      - mongo

  managr-api:
    env_file: .env
    restart: always
    build: ./apps/managr-api
    environment:
      PORT: 3092
    ports:
      - "3092:3092"
    networks:
      - api-network
    depends_on:
      - mongo
      - redis

  mongo:
    image: 'mongo:latest'
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
    ports:
      - 27029:27017
    volumes:
      - ./data/mongo:/bitnami/mongodb
      - ./data/mongo/init-mongo.js:/docker-entrypoint-inidb.d/init-mongo.js:ro
    networks:
      - api-network

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - api-network
    volumes:
      - ./data/redis:/bitnami/redis

  webserver:
    depends_on:
      - canto
      - boheme
      - jazzola
      - managr
      - managr-api
      - swing-family
      - trio-rsh
      - west-side-trio
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d:ro
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/certbot:/var/www/certbot
      - ./data/static:/static
    networks:
      - api-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/certbot:/var/www/certbot


