// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/galerie": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/galerie" | "/robots.txt" | "/sitemap.xml" | "/*";
  };
  "./routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "./routes/galerie.tsx": {
    id: "routes/galerie";
    page: "/galerie";
  };
  "./routes/robots.txt.tsx": {
    id: "routes/robots.txt";
    page: "/robots.txt";
  };
  "./routes/sitemap.xml.tsx": {
    id: "routes/sitemap.xml";
    page: "/sitemap.xml";
  };
  "./routes/__catchall.tsx": {
    id: "routes/__catchall";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/./routes/index.tsx");
  "routes/galerie": typeof import("./app/./routes/galerie.tsx");
  "routes/robots.txt": typeof import("./app/./routes/robots.txt.tsx");
  "routes/sitemap.xml": typeof import("./app/./routes/sitemap.xml.tsx");
  "routes/__catchall": typeof import("./app/./routes/__catchall.tsx");
};