// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/musicians": {
    params: {};
  };
  "/tour": {
    params: {};
  };
  "/music": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/musicians" | "/tour" | "/music" | "/contact" | "/*";
  };
  "./routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "./routes/musicians.tsx": {
    id: "routes/musicians";
    page: "/musicians";
  };
  "./routes/tour.tsx": {
    id: "routes/tour";
    page: "/tour";
  };
  "./routes/music.tsx": {
    id: "routes/music";
    page: "/music";
  };
  "./routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "./routes/__catchall.tsx": {
    id: "routes/__catchall";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/./routes/index.tsx");
  "routes/musicians": typeof import("./app/./routes/musicians.tsx");
  "routes/tour": typeof import("./app/./routes/tour.tsx");
  "routes/music": typeof import("./app/./routes/music.tsx");
  "routes/contact": typeof import("./app/./routes/contact.tsx");
  "routes/__catchall": typeof import("./app/./routes/__catchall.tsx");
};