// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/$subdomain": {
    params: {};
  };
  "/$subdomain/musicians": {
    params: {};
  };
  "/$subdomain/tour": {
    params: {};
  };
  "/$subdomain/music": {
    params: {};
  };
  "/$subdomain/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/$subdomain" | "/$subdomain/musicians" | "/$subdomain/tour" | "/$subdomain/music" | "/$subdomain/contact";
  };
  "./routes/$subdomain/index.tsx": {
    id: "routes/$subdomain/index";
    page: "/$subdomain" | "/$subdomain/musicians" | "/$subdomain/tour" | "/$subdomain/music" | "/$subdomain/contact";
  };
  "./routes/$subdomain/musicians.tsx": {
    id: "routes/$subdomain/musicians";
    page: "/$subdomain/musicians";
  };
  "./routes/$subdomain/tour.tsx": {
    id: "routes/$subdomain/tour";
    page: "/$subdomain/tour";
  };
  "./routes/$subdomain/music.tsx": {
    id: "routes/$subdomain/music";
    page: "/$subdomain/music";
  };
  "./routes/$subdomain/contact.tsx": {
    id: "routes/$subdomain/contact";
    page: "/$subdomain/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/$subdomain/index": typeof import("./app/./routes/$subdomain/index.tsx");
  "routes/$subdomain/musicians": typeof import("./app/./routes/$subdomain/musicians.tsx");
  "routes/$subdomain/tour": typeof import("./app/./routes/$subdomain/tour.tsx");
  "routes/$subdomain/music": typeof import("./app/./routes/$subdomain/music.tsx");
  "routes/$subdomain/contact": typeof import("./app/./routes/$subdomain/contact.tsx");
};